### ISSUE TITLE
hdmi无法使用

### ISSUE THREAD

**Issue by lyydhy** [SnowsonZ/MateBookD-EFI#1]
大佬 我是同本子的i5款  hdmi无法使用 有啥办法吗？ 还有就是本子关闭显示器时间久了候 就打不开了 得强制重启

**Comment by SnowsonZ** [comment]
盒盖睡眠后，需要开合2次正常亮屏，这个现在没办法。

hdmi我没测试，等我测试下回复你。

**Comment by SnowsonZ** [comment]
> 大佬 我是同本子的i5款 hdmi无法使用 有啥办法吗？ 还有就是本子关闭显示器时间久了候 就打不开了 得强制重启


 盒盖睡眠后，需要开合2次正常亮屏，这个现在没办法。
hdmi我没测试，等我测试下回复你。

**Comment by lyydhy** [comment]
好的

**Comment by lyydhy** [comment]
https://github.com/Zero-zer0/Matebook_D_2018_Hackintosh_OpenCore  盒盖你可以看看这个的 他的盒盖睡眠 和 hdmi 都是好的  就是没更新了

**Comment by shuatv** [comment]
hdmi我用了可以

**Comment by shuatv** [comment]
这个算是我用过的最完美的efi了，感谢作者

**Comment by SnowsonZ** [comment]
> 这个算是我用过的最完美的efi了，感谢作者

ok   @lyydhy

**Comment by lyydhy** [comment]
好的  我明天在试试

**Comment by lyydhy** [comment]
虽然我不知道那位兄弟为啥可以 但是确实我电脑的确HDMI 不行  我周末自己研究一哈把  谢谢作者

**Comment by SnowsonZ** [comment]
> 虽然我不知道那位兄弟为啥可以 但是确实我电脑的确HDMI 不行 我周末自己研究一哈把 谢谢作者

可能与MBP取消接口有关系，可以按下图修改下EFI中的机型配置试一下。修改完连接外接屏后，我这出现笔记本黑屏，外接屏正常，来回切换下刷新率就可以了。

![device_info](https://user-images.githubusercontent.com/12555482/100333425-8b04fc80-300d-11eb-950b-01685fdb992b.png)

**Comment by lyydhy** [comment]
确实可以显示了  但是不知道为啥 主显示器 有明显的卡顿

**Comment by lyydhy** [comment]
而  副屏一点都不卡
