### ISSUE TITLE
无法进入安装界面

### ISSUE THREAD

**Issue by lyydhy** [SnowsonZ/MateBookD-EFI#12]
![IMG_20211016_012040](https://user-images.githubusercontent.com/19465770/137528902-d6ed2eff-a8b2-414f-b6e9-88a8c6d0af20.jpg)
 错误如图

**Comment by SnowsonZ** [comment]
> ![IMG_20211016_012040](https://user-images.githubusercontent.com/19465770/137528902-d6ed2eff-a8b2-414f-b6e9-88a8c6d0af20.jpg)
> 错误如图

OTA升级吗？当前是什么版本？

**Comment by lyydhy** [comment]
> > ![IMG_20211016_012040](https://user-images.githubusercontent.com/19465770/137528902-d6ed2eff-a8b2-414f-b6e9-88a8c6d0af20.jpg)
> > 错误如图
> 
> OTA升级吗？当前是什么版本？bigsur 11.6

全新安装

**Comment by SnowsonZ** [comment]
> > > ![IMG_20211016_012040](https://user-images.githubusercontent.com/19465770/137528902-d6ed2eff-a8b2-414f-b6e9-88a8c6d0af20.jpg)
> > > 错误如图
> > 
> > 
> > OTA升级吗？当前是什么版本？bigsur 11.6
> 
> 全新安装

> > > ![IMG_20211016_012040](https://user-images.githubusercontent.com/19465770/137528902-d6ed2eff-a8b2-414f-b6e9-88a8c6d0af20.jpg)
> > > 错误如图
> > 
> > 
> > OTA升级吗？当前是什么版本？bigsur 11.6
> 
> 全新安装

刚特意又试了下，没遇到你这个问题。我是11.1升级到11.6.1。先扒一下远景看有没有类似的问题。实在没有别的办法你先安装个11.1，然后OTA吧。讲道理应该没得问题才对。

<img width="698" alt="image" src="https://user-images.githubusercontent.com/12555482/137637076-56cfe991-c0cd-44a3-9dfb-957287208fd1.png">

**Comment by lyydhy** [comment]
刚试了一下  还是不行 镜像是（macOS Big Sur 11.1 20C69 Installer for CLOVER 5127 and WEPE） 错误还是跟上面的一样
但是我用以前的efi就可以进入安装界面
[EFI 2.zip](https://github.com/SnowsonZ/MateBookD-EFI/files/7382955/EFI.2.zip)

**Comment by lyydhy** [comment]
以前的efi 我换了一下网卡驱动 因为我电脑之前把网卡换成了dw1560  其他的我就没改了 不知道是不是这个问题

**Comment by SnowsonZ** [comment]
> 以前的efi 我换了一下网卡驱动 因为我电脑之前把网卡换成了dw1560 其他的我就没改了 不知道是不是这个问题

昨晚我更新bios1.35后发现了和你类似的问题，不知道你是不是因为这个。我刚提交了修复版本的EFI(bios_1.35分支)，你可以试下看。

**Comment by SnowsonZ** [comment]
> 以前的efi 我换了一下网卡驱动 因为我电脑之前把网卡换成了dw1560 其他的我就没改了 不知道是不是这个问题

我遇到的问题
![DCIM](https://user-images.githubusercontent.com/12555482/140502237-209aebcd-9fde-4a60-b469-3df94f1fa4f4.jpg)

**Comment by SnowsonZ** [comment]
fixed
