### ISSUE TITLE
发现触摸板经过一定时间后无法使用 必须要重启

### ISSUE THREAD

**Issue by shuatv** [SnowsonZ/MateBookD-EFI#2]
首先感谢SnowsonZ的这个EFI，整体来说非常完美。

我的是MATEBOOKD D 2018 i5 8250U低配版，无独显。

个人使用习惯是合盖不关机。用了这个efi后发现，经过一段时间后，可能是半天的样子，触摸板无法使用，重启则恢复正常。然后再经过半天后再次触摸板无法使用。

**Comment by SnowsonZ** [comment]
> 首先感谢SnowsonZ的这个EFI，整体来说非常完美。
> 
> 我的是MATEBOOKD D 2018 i5 8250U低配版，无独显。
> 
> 个人使用习惯是合盖不关机。用了这个efi后发现，经过一段时间后，可能是半天的样子，触摸板无法使用，重启则恢复正常。然后再经过半天后再次触摸板无法使用。

我这边也偶尔会出现触摸板失灵的现象，不过没有这么频繁，大概是使用了1个月，出现过2次。
等待触摸板驱动更新，或者可能可以通过修改DSDT文件可以修复，可以试试。

**Comment by shuatv** [comment]
> > 首先感谢SnowsonZ的这个EFI，整体来说非常完美。
> > 我的是MATEBOOKD D 2018 i5 8250U低配版，无独显。
> > 个人使用习惯是合盖不关机。用了这个efi后发现，经过一段时间后，可能是半天的样子，触摸板无法使用，重启则恢复正常。然后再经过半天后再次触摸板无法使用。
> 
> 我这边也偶尔会出现触摸板失灵的现象，不过没有这么频繁，大概是使用了1个月，出现过2次。
> 等待触摸板驱动更新，或者可能可以通过修改DSDT文件可以修复，可以试试。

https://www.zhihu.com/question/390800640

今天按照知乎这个帖子，把里头能做的设置全做了后，超过10小时触摸板OK

**Comment by SnowsonZ** [comment]
> > > 首先感谢SnowsonZ的这个EFI，整体来说非常完美。
> > > 我的是MATEBOOKD D 2018 i5 8250U低配版，无独显。
> > > 个人使用习惯是合盖不关机。用了这个efi后发现，经过一段时间后，可能是半天的样子，触摸板无法使用，重启则恢复正常。然后再经过半天后再次触摸板无法使用。
> > 
> > 
> > 我这边也偶尔会出现触摸板失灵的现象，不过没有这么频繁，大概是使用了1个月，出现过2次。
> > 等待触摸板驱动更新，或者可能可以通过修改DSDT文件可以修复，可以试试。
> 
> https://www.zhihu.com/question/390800640
> 
> 今天按照知乎这个帖子，把里头能做的设置全做了后，超过10小时触摸板OK

ok
