### ISSUE TITLE
蓝牙鼠标无法连接

### ISSUE THREAD

**Issue by adhyc520** [SnowsonZ/MateBookD-EFI#3]
i5 2018款，蓝牙耳机正常使用，蓝牙鼠标连接不上。

**Comment by SnowsonZ** [comment]
> i5 2018款，蓝牙耳机正常使用，蓝牙鼠标连接不上。

驱动问题，蓝牙4.0的设备可以连接，但无法使用，只能等待大佬的驱动修复，可移步关注 https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/51

**Comment by adhyc520** [comment]
> > i5 2018款，蓝牙耳机正常使用，蓝牙鼠标连接不上。
> 
> 驱动问题，蓝牙4.0的设备可以连接，但无法使用，只能等待大佬的驱动修复，可移步关注 [OpenIntelWireless/IntelBluetoothFirmware#51](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/51)

您这边有出现睡眠后唤醒后，屏幕缩小显示，为不知道是不是为开hidip的问题

**Comment by adhyc520** [comment]
> > > i5 2018款，蓝牙耳机正常使用，蓝牙鼠标连接不上。
> > 
> > 
> > 驱动问题，蓝牙4.0的设备可以连接，但无法使用，只能等待大佬的驱动修复，可移步关注 [OpenIntelWireless/IntelBluetoothFirmware#51](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/51)
> 
> 您这边有出现睡眠后唤醒后，屏幕缩小显示，为不知道是不是为开hidip的问题

还有个问题，总觉得网速很慢，测速后网速只有原来的一半左右，请问是不是网卡驱动的问题

**Comment by SnowsonZ** [comment]
> > > i5 2018款，蓝牙耳机正常使用，蓝牙鼠标连接不上。
> > 
> > 
> > 驱动问题，蓝牙4.0的设备可以连接，但无法使用，只能等待大佬的驱动修复，可移步关注 [OpenIntelWireless/IntelBluetoothFirmware#51](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/51)
> 
> 您这边有出现睡眠后唤醒后，屏幕缩小显示，为不知道是不是为开hidip的问题

试了下，确实会有该问题，使用hidpi修复选项也不行，建议寻求hidpi大佬解决

**Comment by SnowsonZ** [comment]
> > > > i5 2018款，蓝牙耳机正常使用，蓝牙鼠标连接不上。
> > > 
> > > 
> > > 驱动问题，蓝牙4.0的设备可以连接，但无法使用，只能等待大佬的驱动修复，可移步关注 [OpenIntelWireless/IntelBluetoothFirmware#51](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/51)
> > 
> > 
> > 您这边有出现睡眠后唤醒后，屏幕缩小显示，为不知道是不是为开hidip的问题
> 
> 试了下，确实会有该问题，使用hidpi修复选项也不行，建议寻求hidpi大佬解决



> > > > i5 2018款，蓝牙耳机正常使用，蓝牙鼠标连接不上。
> > > 
> > > 
> > > 驱动问题，蓝牙4.0的设备可以连接，但无法使用，只能等待大佬的驱动修复，可移步关注 [OpenIntelWireless/IntelBluetoothFirmware#51](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/51)
> > 
> > 
> > 您这边有出现睡眠后唤醒后，屏幕缩小显示，为不知道是不是为开hidip的问题
> 
> 还有个问题，总觉得网速很慢，测速后网速只有原来的一半左右，请问是不是网卡驱动的问题

我这没发现这个问题，不过偶尔存在不太稳定的现象。建议问一下开发该驱动的大佬  [OpenIntelWireless/itlwm](https://github.com/OpenIntelWireless/itlwm)
