### ISSUE TITLE
无法引导win10，出现“ACPI_BIOS_ERROR”

### ISSUE THREAD

**Issue by leizh19941204** [SnowsonZ/MateBookD-EFI#4]
使用该EFI引导win10系统时无法进入，出现错误“ACPI_BIOS_ERROR”

**Comment by SnowsonZ** [comment]
大哥，你走错门了。

**Comment by leizh19941204** [comment]
啊，不能引导的吗？哈哈，我想双系统哎，不能实现吗？

**Comment by SnowsonZ** [comment]
> 啊，不能引导的吗？哈哈，我想双系统哎，不能实现吗？

目前这个EFI只支持mac系统引导，win需要加入引导文件。

**Comment by leizh19941204** [comment]
> 目前这个EFI只支持mac系统引导，win需要加入引导文件。

我把win的引导文件Microsoft文件夹加入到该EFI下，开机时选择win，出现ACPI_BIOS_ERROR
这个有方法解决吗？

**Comment by SnowsonZ** [comment]
> > 目前这个EFI只支持mac系统引导，win需要加入引导文件。
> 
> 我把win的引导文件Microsoft文件夹加入到该EFI下，开机时选择win，出现ACPI_BIOS_ERROR
> 这个有方法解决吗？

B站有双系统引导教程，我没试过

**Comment by leizh19941204** [comment]
> > > 目前这个EFI只支持mac系统引导，win需要加入引导文件。
> > 
> > 
> > 我把win的引导文件Microsoft文件夹加入到该EFI下，开机时选择win，出现ACPI_BIOS_ERROR
> > 这个有方法解决吗？
> 
> B站有双系统引导教程，我没试过


好的，谢谢大神回复
