### ISSUE TITLE
新版本无法引导安装

### ISSUE THREAD

**Issue by vfxh** [SnowsonZ/MateBookD-EFI#7]
更新了之后，新版本无法引导安装了。制作U盘启动，然后导入EFI到esp分区。开机进入U盘，没办法进入安装界面，直接重启

**Comment by wuyan-si** [comment]
不支持升级版本

**Comment by vfxh** [comment]
> 不支持升级版本
哦，是只能11.0.1。11.1不行是吧

**Comment by SnowsonZ** [comment]
@vfxh @vfxh 已支持11.0.1 升级11.1，其实更新下kext就可以了。
