### ISSUE TITLE
求更新20D75的oc

### ISSUE THREAD

**Issue by adhyc520** [SnowsonZ/MateBookD-EFI#8]
用其他oc无法使用Wi-Fi，求更新。

**Comment by shuatv** [comment]
和OC没关系吧，我用的20D75，WiFi一切正常，不过我是用的DW1820网卡

**Comment by adhyc520** [comment]
我这边无法正常启动，不知道是不是没修改BIOS，您修改了吗？ @shuatv

**Comment by shuatv** [comment]
> 我这边无法正常启动，不知道是不是没修改BIOS，您修改了吗？ @shuatv

改了BIOS和显卡，不过这两样和启动也没关系。估计是boot-args参数配置问题吧

**Comment by adhyc520** [comment]
您

> > 我这边无法正常启动，不知道是不是没修改BIOS，您修改了吗？ @shuatv
> 
> 改了BIOS和显卡，不过这两样和启动也没关系。估计是boot-args参数配置问题吧

您是i7还是i5，我是i5之前可以用。

**Comment by shuatv** [comment]
> 您
> 
> > > 我这边无法正常启动，不知道是不是没修改BIOS，您修改了吗？ @shuatv
> > 
> > 
> > 改了BIOS和显卡，不过这两样和启动也没关系。估计是boot-args参数配置问题吧
> 
> 您是i7还是i5，我是i5之前可以用。

i5 8250U，8GB+8GB内存，加了一块Intel 480G的SATA SD，换了DW1820无线网卡

**Comment by SnowsonZ** [comment]
> 您
> 
> > > 我这边无法正常启动，不知道是不是没修改BIOS，您修改了吗？ @shuatv
> > 
> > 
> > 改了BIOS和显卡，不过这两样和启动也没关系。估计是boot-args参数配置问题吧
> 
> 您是i7还是i5，我是i5之前可以用。

系统版本是？OC的升级自行搜索教程，还是比较多的。

**Comment by SnowsonZ** [comment]
> 我这边无法正常启动，不知道是不是没修改BIOS，您修改了吗？ @shuatv

不清楚你说的BIOS是修改了什么，repo里的BIOS工具包是为外接4K显示器用的，没有需求可以忽略

**Comment by adhyc520** [comment]
> > 我这边无法正常启动，不知道是不是没修改BIOS，您修改了吗？ @shuatv
> 
> 不清楚你说的BIOS是修改了什么，repo里的BIOS工具包是为外接4K显示器用的，没有需求可以忽略

那我啥也没改，0.6.3的时候可以直接替换您的efi可用，现在替换进度条走一半就重启，然后显示无法启动。

**Comment by shuatv** [comment]
> > > 我这边无法正常启动，不知道是不是没修改BIOS，您修改了吗？ @shuatv
> > 
> > 
> > 不清楚你说的BIOS是修改了什么，repo里的BIOS工具包是为外接4K显示器用的，没有需求可以忽略
> 
> 那我啥也没改，0.6.3的时候可以直接替换您的efi可用，现在替换进度条走一半就重启，然后显示无法启动。

建议用OpenCore configurator打开0.6.3 和0.6.4的config.plist文件，逐项比对修改为何0.6.3的一致，这样应该能启动
